USE [master]
GO

/****** Object:  Database [NancyAzureFileUpload]    Script Date: 1/20/2017 12:06:46 AM ******/
CREATE DATABASE [NancyAzureFileUpload]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NancyAzureFileUpload', FILENAME = N'C:\Users\Fernando\NancyAzureFileUpload.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NancyAzureFileUpload_log', FILENAME = N'C:\Users\Fernando\NancyAzureFileUpload_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NancyAzureFileUpload].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NancyAzureFileUpload] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET ARITHABORT OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NancyAzureFileUpload] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NancyAzureFileUpload] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NancyAzureFileUpload] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NancyAzureFileUpload] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NancyAzureFileUpload] SET  MULTI_USER 
GO

ALTER DATABASE [NancyAzureFileUpload] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NancyAzureFileUpload] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NancyAzureFileUpload] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NancyAzureFileUpload] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NancyAzureFileUpload] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NancyAzureFileUpload] SET  READ_WRITE 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[Files](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DispatchId] [int] NULL,
	[PrimaryUrl] [varchar](1024) NULL,
	[SecondaryUrl] [varchar](1024) NULL,
	[ItemType] [varchar](50) NULL,
	[Filename] [varchar](125) NULL,
	[Filetype] [varchar](50) NULL,
	[Timestamp] [datetime] NOT NULL
)

GO

SET ANSI_PADDING OFF
GO
